### ISSUE TITLE
Default format for the -f arguments

### ISSUE THREAD

**Issue by farhansj** [PU-SDS/DiMA#24]
Hi,

Can you implement a default format for the -f arguments?

So, if the user provides the -he arguments but didn't provide the -f arguments, then the software shall assume

the metadata/header order in the input file is following the default format.

Thank you

**Comment by ShanWeera** [comment]
> Hi,
> 
> Can you implement a default format for the -f arguments?
> 
> So, if the user provides the -he arguments but didn't provide the -f arguments, then the software shall assume
> 
> the metadata/header order in the input file is following the default format.
> 
> Thank you

In the new version, we will be removing the `-he` parameter (issue https://github.com/PU-SDS/DiMA/issues/26). So, the only way that we know tha the user wants to decode the headers is by checking if the `-f` parameter is *not* null. 

Any ideas how we can still have a default format (or if we need a default format at all) with `header_decode`/`-he` parameter no longer there?
