### ISSUE TITLE
Load Sample Data on Web Server

### ISSUE THREAD

**Issue by eselimnl** [PU-SDS/DiMA#48]
We need to allow users to do an analysis on DiMA with a sample dataset.

On the front page, once the user clicks on the "Load Sample Data" button, all the input parameters should be auto-filled and the data should be uploaded.

HCV NS3 (Sample 1):

Protein name: HCV NS3
Kmer: 9
Low support: 30
Data: will send privately

CHKIV nsP1 (Sample 2):

Protein name: CHIKV nsP1
Kmer: 9
Low support: 30
Data: will send privately

**Comment by ShanWeera** [comment]
> We need to allow users to do an analysis on DiMA with a sample dataset.
> 
> On the front page, once the user clicks on the "Load Sample Data" button, all the input parameters should be auto-filled and the data should be uploaded.
> 
> HCV NS3 (Sample 1):
> 
> Protein name: HCV NS3 Kmer: 9 Low support: 30 Data: will send privately
> 
> CHKIV nsP1 (Sample 2):
> 
> Protein name: CHIKV nsP1 Kmer: 9 Low support: 30 Data: will send privately

We good on this man?. It doesn't "auto load" but I think it's good enough for now. What you think?

**Comment by eselimnl** [comment]
I think it is enough for now.
