### ISSUE TITLE
Support for nucleotides

### ISSUE THREAD

**Issue by ShanWeera** [PU-SDS/DiMA#55]
The diagnostics module will be focusing on nucleotides and DiMA will need to support nucleotides as well. The current algorithm is agnostic, but the ambiguous characters will need to be defined separately for nucleotides and proteins as there is some overlap between the two.

The ambiguous characters for proteins is a list of characters that should be considered invalid, but for NT a better approach is to label everything other than A, T, G, C, U as ambiguous.

**Comment by eselimnl** [comment]
We may require an input parameter to define the type of analysis: `DNA` or `Protein` . 
Auto-detection was another idea.

**Comment by eselimnl** [comment]
After implementing this, it becomes relevant that all the “protein” labels should be converted to a generic word (on the parameters and result pages), which has decided as “query”.
![163CB9A0-A7AA-4C45-941E-BF023A7B1D2C](https://user-images.githubusercontent.com/63191434/157377990-ed23d052-8fc8-4e84-83f7-47e3519354a9.jpeg)
